fix CORS error in production (#87)
* test CORS change to production

* also forward PORT 5000 for API

* add proxy to package.josn

* add CORS header to WEBPACK config

* fix yml typo in workflow

* remove CORS header from end-to-end testing webpack config

* add seperate dev build for e2e testing

* use Docker.dev for end-to-end testing

* client tweaks for image file alert

* edit persistent alert message error

* remove TEMP production push

* test production workflow

* test production workflow

* fix broken createNotif reference

* test production workflow

* remove temporary production workflow on dev branch

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -292,7 +292,7 @@ jobs:
             # if docker_tag_exists ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CLIENT_REPO }} latest; then
             #     echo "✅ Found Docker Image on DockerHub"
             # else
-            #     (echo "❌ Unable to find ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CLIENT_REPO }} on DockerHub" && exit 1)
+            #     (echo "❌ Unable to find ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CLIENT_REPO }} on DockerHub?" && exit 1)
             # fi
 
             if docker_tag_exists ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_SERVER_REPO }} latest; then
@@ -383,4 +383,5 @@ jobs:
 
             echo -e "$BLUE Started up latest Server image $NC"
             sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000
+            sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 5000 -j REDIRECT --to-port 5000
             echo -e "$GREEN EC2 deployment complete! $NC"
